# Generated by Django 4.1.5 on 2023-01-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_batch', models.CharField(default='', max_length=60)),
                ('student_enrol_no', models.IntegerField(default=0)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
