# Generated by Django 4.1.5 on 2023-01-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=60)),
                ('password', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
