# Generated by Django 4.1.5 on 2023-01-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_login_alter_student_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
