# Generated by Django 4.1.5 on 2023-01-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_login_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFileData',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(default='', max_length=100)),
                ('student_batch', models.CharField(default='', max_length=60)),
                ('student_enrol_no', models.IntegerField(default=0)),
            ],
        ),
    ]
