# Generated by Django 4.1.5 on 2023-02-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_uploadedfiledata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='flag',
        ),
        migrations.AddField(
            model_name='login',
            name='user_type',
            field=models.CharField(default='', max_length=60),
        ),
    ]
