# Generated by Django 4.1.5 on 2023-02-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_login_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='user_type',
            field=models.CharField(choices=[('HOD', 'HOD'), ('S', 'Student'), ('T', 'Teacher')], default='', max_length=10),
        ),
    ]
