# Generated by Django 4.1.5 on 2023-02-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_login_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=60)),
                ('password', models.CharField(default='', max_length=60)),
                ('user_type', models.CharField(choices=[('HOD', 'HOD'), ('Student', 'Student'), ('Teacher', 'Teacher')], default='', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
