# Generated by Django 4.1.5 on 2023-02-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_user_login_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='user_type',
            field=models.IntegerField(default=''),
        ),
    ]
