# Generated by Django 4.1.5 on 2023-02-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_user_login_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Login',
            new_name='User',
        ),
    ]
