# Generated by Django 4.1.5 on 2023-02-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_user_login_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LoginUser',
        ),
    ]
