# Generated by Django 4.1.5 on 2023-02-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_delete_uploadedfiledata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
