# Generated by Django 4.1.5 on 2023-02-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
