# Generated by Django 4.1.5 on 2023-02-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_student_student_depart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pub_date',
        ),
    ]
